app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for,jsonify, session as session_flask
from .conn import session, User, Ratings
from app.services import ApiFilmesService
from app.services import RecomendadorDeFilmesService
import pandas as pd
import bcrypt

main = Blueprint('main',__name__)
api_key = '32fca79cddd1530919c06027ce60b04e'
api_service = ApiFilmesService(api_key)

# Inicialize o treinamento do modelo
recomendador = RecomendadorDeFilmesService()
recomendador.verificar_ou_treinar_modelo()

@main.route('/')
def index():
    return render_template('index.html')

# ---------------------- ROTAS DE AUTENTICAÇÃO E CADASTRO --------------------------------@main.route('/entrar', methods=['POST'])
@main.route('/entrar', methods=['POST'])
def logar():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('senha').strip()  # Remove espaços desnecessários
    else:
        return redirect(url_for('main.index'))

    # Verifica se o usuário existe
    usuario_existente = session.query(User).filter_by(email=email).first()
    
    if usuario_existente:
        print(f"Senha inserida pelo usuário: {password}")
        print(f"Hash do banco de dados: {usuario_existente.password}")

        # Verifica se a senha está correta
        if bcrypt.checkpw(password.encode('utf-8'), usuario_existente.password.encode('utf-8')):
            nome = usuario_existente.username
            usuario_id = usuario_existente.user_id
            session_flask['usuario_id'] = usuario_id

            # Recupera as avaliações do filme pelo user_id
            avaliacoes = session.query(Ratings).filter_by(user_id=usuario_id).all()

            # Buscar as avaliações do banco de dados
            avaliacoes_usuario = [
                {
                    'movie_api_id': avaliacao.movie_api_id,
                    'rating': avaliacao.rating
                }
                for avaliacao in avaliacoes
            ]
            recomendacoes_ids = recomendador.recomendar_filmes_hibrido(usuario_id, avaliacoes_usuario)
            
            # Agora, obtemos os detalhes dos filmes recomendados usando o método da API
            filmes_recomendados = []
            for recomendacao in recomendacoes_ids:
                filme = recomendacao
                filmes_recomendados.append(filme)

            # Renderiza a página de filmes com os filmes recomendados
            return render_template('filmes.html', nome=nome, email=email, usuario_id=usuario_id, filmes_recomendados=filmes_recomendados)
    
    error = 'Email ou senha inválido'
    return render_template('index.html', error=error)


#rota para sair e encerrar sessão
@main.route('/sair')
def sair():
    session_flask.clear()
    return redirect(url_for('main.index'))

# Rota para retornar para a página filmes
@main.route('/filmes')
def filmes():
    nome = session_flask.get('nome')
    usuario_id = session_flask.get('usuario_id')
    
    try:
        # Recupera as avaliações do filme pelo user_id
        avaliacoes = session.query(Ratings).filter_by(user_id=usuario_id).all()

        # Buscar as avaliações do banco de dados
        avaliacoes_usuario = [
            {
                'movie_api_id': avaliacao.movie_api_id,
                'rating': avaliacao.rating
            }
            for avaliacao in avaliacoes
        ]
        recomendacoes_ids = recomendador.recomendar_filmes_hibrido(usuario_id, avaliacoes_usuario)
        
        # Agora, obtemos os detalhes dos filmes recomendados usando o método da API
        filmes_recomendados = []
        for recomendacao in recomendacoes_ids:
            filme = recomendacao
            filmes_recomendados.append(filme)
        
        # Renderiza a página de filmes com os filmes recomendados
        return render_template('filmes.html', nome=nome, usuario_id=usuario_id, filmes_recomendados=filmes_recomendados)
    except Exception as e:
        return render_template('filmes.html', nome=nome, usuario_id=usuario_id, error=f'Erro ao recuperar filmes recomendados: {e}')
    
@main.route('/cadastrar', methods=['POST'])
def cadastrar():
    if request.method == 'POST':
        nome = request.form.get('nome_cadastro')
        email = request.form.get('email_cadastro')
        senha = request.form.get('senha_cadastro')
        senhaConfirmada = request.form.get('confirm_senha')

        if senha == senhaConfirmada:
            if session.query(User).filter_by(email=email).first():
                error = 'Email já cadastrado'
                return render_template('index.html', error=error)
            
            # Hashear a senha
            senha_hash = bcrypt.hashpw(senha.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
            
            # Criar o novo usuário
            novo_usuario = User(username=nome, email=email, password=senha_hash)
            session.add(novo_usuario)
            session.commit()
            sucess = 'Usuário cadastrado com sucesso, faça seu login!'
            return redirect(url_for('main.index', sucess=sucess))
        else:
            error = 'Senhas não conferem'
            return redirect(url_for('main.index', error=error))
    
# ---------------------- ROTAS FILMES --------------------------------
@main.route('/pesquisar', methods=['POST'])
def pesquisar():
    nome_filme = request.form.get('nome_filme')
    nome = session_flask.get('nome')
    usuario_id = session_flask.get('usuario_id')
    try:
        resultados = api_service.filtrar_filmes(nome_filme)
        
        # Recupera as avaliações do filme pelo user_id
        avaliacoes = session.query(Ratings).filter_by(user_id=usuario_id).all()

        # Buscar as avaliações do banco de dados
        avaliacoes_usuario = [
            {
                'movie_api_id': avaliacao.movie_api_id,
                'rating': avaliacao.rating
            }
            for avaliacao in avaliacoes
        ]
        recomendacoes_ids = recomendador.recomendar_filmes_hibrido(usuario_id, avaliacoes_usuario)
        
        # Agora, obtemos os detalhes dos filmes recomendados usando o método da API
        filmes_recomendados = []
        for recomendacao in recomendacoes_ids:
            filme = recomendacao
            filmes_recomendados.append(filme)
            
        return render_template('filmes.html', nome=nome, id=usuario_id, resultados=resultados.get('results', []), filmes_recomendados=filmes_recomendados)
    except request.exceptions.HTTPError as e:
        return render_template('filmes.html', nome=nome, id=usuario_id, error=f'Erro na requisição: {e}')
    
@main.route('/filme/<int:id>', methods=['GET'])
def get_filme(id):
    filme = api_service.get_filme_by_id(id)
    return render_template('filme.html', filme=filme)

# Rota de avaliação do filme
@main.route('/filme/avaliar/<int:id>', methods=['POST'])
def avaliar_filme(id):
    if request.method == 'POST':
        # Recebe a avaliação do formulário
        rating_value = request.form.get('rating', type=float)
        usuario_id = session_flask.get('usuario_id')

        if not usuario_id:
            error = 'Usuário não autenticado'
            return redirect(url_for('main.index', error=error))

        if not (0.0 <= rating_value <= 5.0):
            error = 'A avaliação deve estar entre 0.0 e 5.0'
            return redirect(url_for('main.filmes', id=id, error=error))

        # Verifica se o filme já existe no dataset
        caminho_movies_path = recomendador.caminho_movies()
        try:
            df_movies = pd.read_csv(caminho_movies_path)
        except Exception as e:
            error = f"Erro ao carregar o dataset de filmes: {e}"
            return redirect(url_for('main.index', error=error))
        
        filme_existente = df_movies[df_movies['movieId'] == id]

        if filme_existente.empty:
            # Se o filme não estiver no dataset, buscamos na API
            try:
                api_service_en = ApiFilmesService(api_key, 'en-US')
                filme = api_service_en.get_filme_by_id(id)
                if filme:
                    # Certifique-se de que o filme é um dicionário JSON válido
                    if isinstance(filme, dict) and 'title' in filme and 'genres' in filme:
                        # Extraindo os nomes dos gêneros e juntando-os em uma string
                        genres = [genre['name'] for genre in filme['genres']]
                        genres_str = '|'.join(genres)  # Salvando os gêneros como uma string

                        # Criando o novo filme a ser adicionado ao dataset
                        novo_filme = pd.DataFrame([{
                            'movieId': id,
                            'title': filme['title'],
                            'genres': genres_str  # Salvando os gêneros como uma string
                        }])

                        # Usando pd.concat() para adicionar o novo filme ao dataset
                        df_movies = pd.concat([df_movies, novo_filme], ignore_index=True)

                        # Gravando de volta no CSV
                        df_movies.to_csv(caminho_movies_path, index=False)
                    else:
                        error = 'Estrutura de dados do filme não é válida ou incompleta.'
                        return redirect(url_for('main.index', error=error))
                else:
                    error = 'Filme não encontrado na API externa.'
                    return redirect(url_for('main.index', error=error))
            except Exception as e:
                error = f"Erro ao buscar o filme na API: {e}"
                return redirect(url_for('main.index', error=error))

        # Agora registramos a avaliação do filme
        avaliacao_existente = session.query(Ratings).filter_by(user_id=usuario_id, movie_api_id=id).first()
        if avaliacao_existente:
            # Atualiza a avaliação existente
            avaliacao_existente.rating = rating_value

app/templates/avaliacoes.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minhas Avaliações</title>
    <!-- Link para o CSS externo -->
    <link rel="stylesheet" href="../static/css/avaliacoes.css">
    <link rel="stylesheet" href="../static/css/header.css"> <!-- Link para o CSS externo -->
    <link rel="stylesheet" href="../static/css/global.css"> <!-- Link para o CSS externo -->
</head>

<body>
    <header>
        <nav class="nav-up">
            <ul class="navbar">
                <li class="nav-left">PickFlick</li>
                <li class="nav-middle">
                    <a href="#pesquisar">Pesquisar Filmes</a>
                    <a href="/filmes">Filmes Recomendados</a>
                    <a href="/avaliacoes">Minhas Avaliações</a>
                </li>
                <li class="nav-right">
                    <a href="/sair" class="signup-button" id="openSignupModal">Sair</a>
                    <button class="change-password-button" id="openChangePasswordModal">Alterar Senha</button>
                </li>
            </ul>
        </nav>

        <!-- MODAL CHANGE PASSWORD -->

        <!-- Modal de Alteração de Senha -->
        <div id="changePasswordModal" class="modal">
            <div class="modal-content">
                <span class="close-button" id="closeChangePasswordModal">&times;</span>
                <h2>Alterar Senha</h2>
                <form action="/alterar_senha/{{ usuario_id }}" method="POST">
                    <label for="senhaAtual">Senha Atual:</label>
                    <input type="password" id="senhaAtual" name="senha_atual" required>

                    <label for="novaSenha">Nova Senha:</label>
                    <input type="password" id="novaSenha" name="nova_senha" required>

                    <label for="confirmNovaSenha">Confirme a Nova Senha:</label>
                    <input type="password" id="confirmNovaSenha" name="confirm_nova_senha" required>

                    <button type="submit" class="modal-submit-button">Salvar</button>
                </form>
            </div>
        </div>

        <main>
            <section id="avaliacoes">
                <h2> Minhas Avaliações</h2>
                <!-- Loop para listar avaliações e filmes -->
                {% if avaliacoes %}
                <!-- Loop para listar avaliações e filmes -->
                {% for avaliacao, filme in zip(avaliacoes, filmes) %}
                <div class="card-avaliacao">
                    <div class="info-avaliacao">
                        <h3>{{ filme.title }}</h3>
                        <p><strong>Nota:</strong> {{ avaliacao.rating }} estrelas</p>
                        <p><strong>Avaliado em:</strong> {{ avaliacao.date }}</p>
                    </div>

                    <!-- Estrelas para editar a avaliação -->
                    <form action="{{ url_for('main.editar_avaliacao', id=avaliacao.movie_api_id) }}" method="POST">
                        <div class="avaliacao-filme">
                            <div class="estrelas">
                                <input type="radio" name="rating" id="star5-{{ avaliacao.movie_api_id }}" value="5" {%
                                    if avaliacao.rating==5 %}checked{% endif %} />
                                <label for="star5-{{ avaliacao.movie_api_id }}">&#9733;</label>

                                <input type="radio" name="rating" id="star4-{{ avaliacao.movie_api_id }}" value="4" {%
                                    if avaliacao.rating==4 %}checked{% endif %} />
                                <label for="star4-{{ avaliacao.movie_api_id }}">&#9733;</label>

                                <input type="radio" name="rating" id="star3-{{ avaliacao.movie_api_id }}" value="3" {%
                                    if avaliacao.rating==3 %}checked{% endif %} />
                                <label for="star3-{{ avaliacao.movie_api_id }}">&#9733;</label>

                                <input type="radio" name="rating" id="star2-{{ avaliacao.movie_api_id }}" value="2" {%
                                    if avaliacao.rating==2 %}checked{% endif %} />
                                <label for="star2-{{ avaliacao.movie_api_id }}">&#9733;</label>

                                <input type="radio" name="rating" id="star1-{{ avaliacao.movie_api_id }}" value="1" {%
                                    if avaliacao.rating==1 %}checked{% endif %} />
                                <label for="star1-{{ avaliacao.movie_api_id }}">&#9733;</label>
                            </div>
                            <button id="btnAvaliar" type="submit">Atualizar Avaliação</button>
                        </div>
                    </form>

                    <!-- Botão de deletar avaliação -->
                    <form action="{{ url_for('main.deletar_avaliacao', id=avaliacao.movie_api_id) }}" method="POST">
                        <button type="submit" class="btn-deletar">Deletar Avaliação</button>
                    </form>
                </div>
                {% endfor %}
                {% else %}
                <p>Nenhum filme foi avaliado ainda.</p>
                {% endif %}
            </section>
        </main>

        <footer>
            <p>&copy; 2024 Sistema de Recomendação de Filmes</p>
        </footer>
        <script>
            document.getElementById('openChangePasswordModal').addEventListener('click', () => {
                document.getElementById('changePasswordModal').style.display = 'block';
            });

            document.getElementById('closeChangePasswordModal').addEventListener('click', () => {
                document.getElementById('changePasswordModal').style.display = 'none';
            });

            window.addEventListener('click', (event) => {
                const modal = document.getElementById('changePasswordModal');
                if (event.target === modal) {
                    modal.style.display = 'none';
                }
            });

        </script>
</body>

</html>

app/templates/filme.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes do Filme</title>
    <!-- Link para o CSS externo -->
    <link rel="stylesheet" href="../static/css/filme.css">
    <link rel="stylesheet" href="../static/css/header.css"> <!-- Link para o CSS externo -->
    <link rel="stylesheet" href="../static/css/global.css"> <!-- Link para o CSS externo -->
</head>

<body>
    <header>
        <nav class="nav-up">
            <ul class="navbar">
                <li class="nav-left">PickFlick</li>
                <li class="nav-middle">
                    <a href="#pesquisar">Pesquisar Filmes</a>
                    <a href="/filmes">Filmes Recomendados</a>
                    <a href="/avaliacoes">Minhas Avaliações</a>
                </li>
                <li class="nav-right">
                    <a href="/sair" class="signup-button" id="openLogout">Sair</a>
                    <button class="change-password-button" id="openChangePasswordModal">Alterar Senha</button>
                </li>
            </ul>
        </nav>
        <div class="nav-down">
            <h1>Detalhes do Filme</h1>
            <nav>
                <a href="/filmes">Voltar à Pesquisa</a>
            </nav>
        </div>
    </header>

    <!-- MODAL CHANGE PASSWORD -->

    <!-- Modal de Alteração de Senha -->
    <div id="changePasswordModal" class="modal">
        <div class="modal-content-password">
            <span class="close-button" id="closeChangePasswordModal">&times;</span>
            <h2>Alterar Senha</h2>
            <form action="/alterar_senha/{{ usuario_id }}" method="POST">
                <label for="senhaAtual">Senha Atual:</label>
                <input type="password" id="senhaAtual" name="senha_atual" required>

                <label for="novaSenha">Nova Senha:</label>
                <input type="password" id="novaSenha" name="nova_senha" required>

                <label for="confirmNovaSenha">Confirme a Nova Senha:</label>
                <input type="password" id="confirmNovaSenha" name="confirm_nova_senha" required>

                <button type="submit" class="modal-submit-button">Salvar</button>
            </form>
        </div>
    </div>

    <main>
        <section id="detalhes-filme">
            <div class="card-detalhes">
                <div class="info-filme">
                    <h2>{{ filme.title }}</h2>
                    <p><strong>Gênero:</strong> {{ filme.genres }}</p>
                    <p><strong>Ano de Lançamento:</strong> {{ filme.release_date }}</p>
                    <p><strong>Duração:</strong> {{ filme.runtime }}</p>
                    <p><strong>Diretor:</strong> Nome do Diretor</p>
                    <p><strong>Sinopse:</strong>{{ filme.overview }}</p>
                </div>
                <div class="imagem-filme">
                    <img src="https://image.tmdb.org/t/p/w500{{ filme.poster_path }}" alt="Capa do Filme">
                </div>
            </div>
            <form action="{{ url_for('main.avaliar_filme', id=filme.id) }}" method="POST">
                <div class="avaliacao-filme">
                    <h3>Avaliação:</h3>
                    <div class="estrelas">
                        <input type="radio" name="rating" id="star5" value="5" />
                        <label for="star5">&#9733;</label>

                        <input type="radio" name="rating" id="star4" value="4" />
                        <label for="star4">&#9733;</label>

                        <input type="radio" name="rating" id="star3" value="3" />
                        <label for="star3">&#9733;</label>

                        <input type="radio" name="rating" id="star2" value="2" />
                        <label for="star2">&#9733;</label>

                        <input type="radio" name="rating" id="star1" value="1" />
                        <label for="star1">&#9733;</label>
                    </div>
                    <button id="btnAvaliar" type="submit">Avaliar</button>
                </div>
            </form>



        </section>
    </main>

    <footer>
        <p>&copy; 2024 Sistema de Recomendação de Filmes</p>
    </footer>

    <script src="script.js"></script> <!-- Link para o JavaScript externo -->
    <script>
        document.getElementById('openChangePasswordModal').addEventListener('click', () => {
            document.getElementById('changePasswordModal').style.display = 'block';
        });

        document.getElementById('closeChangePasswordModal').addEventListener('click', () => {
            document.getElementById('changePasswordModal').style.display = 'none';
        });

        window.addEventListener('click', (event) => {
            const modal = document.getElementById('changePasswordModal');
            if (event.target === modal) {
                modal.style.display = 'none';
            }
        });

    </script>
</body>

</html>

app/templates/filmes.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PickFlick - Sistema de Recomendação de Filmes</title>
    <link rel="stylesheet" href="../static/css/header.css">
    <link rel="stylesheet" href="../static/css/filmes.css">
    <link rel="stylesheet" href="../static/css/filmesPesquisados.css">
    <link rel="stylesheet" href="../static/css/global.css">
</head>

<body>
    <header>
        <nav class="nav-up">
            <ul class="navbar">
                <li class="nav-left">PickFlick</li>
                <li class="nav-middle">
                    <a href="#pesquisar">Pesquisar Filmes</a>
                    <a href="/filmes">Filmes Recomendados</a>
                    <a href="/avaliacoes">Minhas Avaliações</a>
                </li>
                <li class="nav-right">
                    <a href="/sair" class="signup-button" id="logout">Sair</a>
                    <button class="change-password-button" id="openChangePasswordModal">Alterar Senha</button>
                </li>
            </ul>
        </nav>
    </header>

    <!-- MODAL CHANGE PASSSWORD -->
    <!-- Modal de Alteração de Senha -->
    <div id="changePasswordModal" class="modal">
        <div class="modal-content-password">
            <span class="close-button" id="closeChangePasswordModal">&times;</span>
            <h2>Alterar Senha</h2>
            <form action="/alterar_senha/{{ usuario_id }}" method="POST">
                <label for="senhaAtual">Senha Atual:</label>
                <input type="password" id="senhaAtual" name="senha_atual" required>

                <label for="novaSenha">Nova Senha:</label>
                <input type="password" id="novaSenha" name="nova_senha" required>

                <label for="confirmNovaSenha">Confirme a Nova Senha:</label>
                <input type="password" id="confirmNovaSenha" name="confirm_nova_senha" required>

                <button type="submit" class="modal-submit-button">Salvar</button>
            </form>
        </div>
    </div>

    <main>
        <!-- Seção de Pesquisa -->
        <section id="pesquisar">
            <h3 style="text-align: center;">Seja Bem-vindo</h3>
            <form id="form-pesquisar" class="form-pesquisar" method="POST" action="{{ url_for('main.pesquisar') }}">
                <input type="text" name="nome_filme" placeholder="Digite o nome do filme...">
                <button type="submit">Pesquisar</button>
            </form>
            <div id="resultados-pesquisa">
                <!-- filmes adicionados dinamicamente -->
                {% if resultados %}
                {% for filme in resultados %}
                <div class="card-filme" data-id="{{ filme.id }}">
                    <img src="https://image.tmdb.org/t/p/w500{{ filme.poster_path }}" alt="Capa do Filme">
                    <h3>{{ filme.title }}</h3>
                    <div class="hover-message">{{ filme.overview }}</div>
                </div>
                {% endfor %}
                {% else %}
                <p>Nenhum resultado encontrado.</p>
                {% endif %}
            </div>
        </section>


        <!-- Seção de Filmes Recomendados -->
        <section id="recomendados">
            <h2>Filmes Recomendados</h2>
            <div id="lista-recomendados">
                {% if filmes_recomendados %}
                {% for filme in filmes_recomendados %}
                <div class="card-filme" data-id="{{ filme.id }}">
                    <img src="../static/assets/capa_recomendados.jpg" alt="Capa do Filme {{ filme.title }}">
                    <h3>{{ filme.title }}</h3>
                    <div class="hover-message">{{ filme.overview }}</div>
                </div>
                {% endfor %}
                {% else %}
                <p>Nenhum filme recomendado no momento. Avalie mais filmes para receber recomendações.</p>
                {% endif %}
            </div>
        </section>

    </main>

    <footer>
        <p>&copy; 2024 Sistema de Recomendação de Filmes</p>
    </footer>

    <script src="../static/js/filmes.js"></script>
    <script>
        document.getElementById('openChangePasswordModal').addEventListener('click', () => {
            document.getElementById('changePasswordModal').style.display = 'block';
        });

        document.getElementById('closeChangePasswordModal').addEventListener('click', () => {
            document.getElementById('changePasswordModal').style.display = 'none';
        });

        window.addEventListener('click', (event) => {
            const modal = document.getElementById('changePasswordModal');
            if (event.target === modal) {
                modal.style.display = 'none';
            }
        });

    </script>
</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PickFlick - Login</title>
    <link rel="stylesheet" href="../static/css/index.css">
</head>

<header>
    <nav>
        <ul class="navbar">
            <li class="nav-left">PickFlick</li>
            <li class="nav-right">
                <a href="#" class="signup-button" id="openSignupModal">Cadastre-se</a>
            </li>
        </ul>
    </nav>
</header>

<body>
    <div class="login-container">
        <form method="POST" action="/entrar" class="login-form">
            <h2>Faça seu login</h2>
            <hr>
            <br>
            <span class="error_message">{{ error }}</span>
            <div class="mb-2">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" placeholder="Digite seu Email" required>
            </div>
            <div class="mb-2">
                <label for="senha">Senha</label>
                <input type="password" id="senha" name="senha" placeholder="Digite sua senha" required>
            </div>
            <a href="#" class="forgot-password">Esqueceu a senha?</a>
            <button type="submit">Entrar</button>
            <a href="#" class="signup-link" id="openSignupModal2">Cadastre-se</a>
        </form>
    </div>

    <!-- Modal de Cadastro -->
    <div id="signupModal" class="modal">
        <div class="modal-content">
            <span class="close" id="closeSignupModal">&times;</span>
            <form class="signup-form" method="post" action="/cadastrar">
                <h2>Cadastre-se</h2>
                <div class="mb-2">
                    <label for="nome_cadastro">Nome</label>
                    <input type="text" id="nome_cadastro" name="nome_cadastro" placeholder="Digite seu nome" required>
                </div>
                <div class="mb-2">
                    <label for="email_cadastro">Email</label>
                    <input type="email" id="email_cadastro" name="email_cadastro" placeholder="Digite seu Email"
                        required>
                </div>
                <div class="mb-2">
                    <label for="senha_cadastro">Senha</label>
                    <input type="password" id="senha_cadastro" name="senha_cadastro" placeholder="Digite sua senha"
                        required>
                </div>
                <div class="mb-2">
                    <label for="confirm_senha">Confirme sua Senha</label>
                    <input type="password" id="confirm_senha" name="confirm_senha" placeholder="Confirme sua senha"
                        required>
                </div>
                <br>
                <div class="mb-2">
                    <button type="submit">Registrar</button>
                </div>
            </form>
        </div>
    </div>
    <footer>
        <p>&copy; 2024 Sistema de Recomendação de Filmes</p>
    </footer>
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
</body>

</html>